# Generated by Django 5.1.15 on 2026-07-06 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True, verbose_name='numero')),
                ('subject', models.CharField(max_length=255, verbose_name='oggetto')),
                ('description', models.TextField(blank=True, verbose_name='descrizione')),
                ('date', models.DateField(verbose_name='data')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='valido fino al')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('sent', 'Inviato'), ('revision', 'Da rivedere'), ('accepted', 'Accettato'), ('rejected', 'Rifiutato'), ('expired', 'Scaduto'), ('cancelled', 'Annullato')], default='draft', max_length=32, verbose_name='stato')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantita')),
                ('preferred_document_profile', models.CharField(choices=[('internal', 'Interno dettagliato'), ('consulting', 'Consulenza'), ('supply', 'Fornitura / artigiano')], default='consulting', max_length=32, verbose_name='profilo documento preferito')),
                ('general_terms', models.TextField(blank=True, verbose_name='condizioni generali')),
                ('internal_notes', models.TextField(blank=True, verbose_name='note interne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='customers.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'preventivo',
                'verbose_name_plural': 'preventivi',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EstimateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrizione')),
                ('process', models.CharField(blank=True, max_length=255, verbose_name='processo')),
                ('treatment', models.CharField(blank=True, max_length=255, verbose_name='trattamento')),
                ('expected_duration', models.CharField(blank=True, max_length=255, verbose_name='durata attesa')),
                ('operating_mode', models.TextField(blank=True, verbose_name='modalita operativa')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantita')),
                ('material_weight_per_unit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='peso materiale per unita')),
                ('machine_time_hours_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ore macchina per unita')),
                ('public_notes', models.TextField(blank=True, verbose_name='note pubbliche')),
                ('internal_notes', models.TextField(blank=True, verbose_name='note interne')),
                ('is_selected', models.BooleanField(default=False, verbose_name='configurazione scelta')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='estimates.estimate', verbose_name='preventivo')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.material', verbose_name='materiale')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.printer', verbose_name='stampante / strumentazione')),
            ],
            options={
                'verbose_name': 'configurazione',
                'verbose_name_plural': 'configurazioni',
                'ordering': ['estimate', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('material', 'Materiale'), ('machine_time', 'Tempo macchina'), ('electricity', 'Elettricita'), ('design', 'Progettazione'), ('setup', 'Setup'), ('labor', 'Manodopera'), ('travel', 'Trasferta'), ('post_processing', 'Post-processing'), ('treatment', 'Trattamento'), ('margin', 'Margine'), ('other', 'Altro')], max_length=32, verbose_name='categoria')),
                ('description', models.CharField(max_length=255, verbose_name='descrizione')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='quantita')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='unita')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo unitario')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='totale')),
                ('visible_internal', models.BooleanField(default=True, verbose_name='visibile interno')),
                ('visible_consulting', models.BooleanField(default=False, verbose_name='visibile consulenza')),
                ('visible_supply', models.BooleanField(default=True, verbose_name='visibile fornitura/artigiano')),
                ('notes', models.TextField(blank=True, verbose_name='note')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='estimates.estimateconfiguration', verbose_name='configurazione')),
            ],
            options={
                'verbose_name': 'voce di costo',
                'verbose_name_plural': 'voci di costo',
                'ordering': ['configuration', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='descrizione')),
                ('internal_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo interno')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='compenso/prezzo')),
                ('status', models.CharField(choices=[('not_planned', 'Non previsto'), ('proposed', 'Proposto'), ('approved', 'Approvato'), ('produced', 'Realizzato'), ('validated', 'Validato'), ('needs_changes', 'Da modificare')], default='not_planned', max_length=32, verbose_name='stato')),
                ('notes', models.TextField(blank=True, verbose_name='note')),
                ('validated_at', models.DateField(blank=True, null=True, verbose_name='data validazione')),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prototype', to='estimates.estimate', verbose_name='preventivo')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.material', verbose_name='materiale')),
            ],
            options={
                'verbose_name': 'prototipo',
                'verbose_name_plural': 'prototipi',
            },
        ),
    ]
