# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="commercial_terms_review_notes",
            field=models.TextField(blank=True, verbose_name="note revisione condizioni cliente"),
        ),
        migrations.AddField(
            model_name="estimate",
            name="commercial_terms_reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="condizioni cliente controllate il"),
        ),
    ]
