# Generated by Django 5.1.15 on 2026-07-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('customer_type', models.CharField(choices=[('person', 'Persona'), ('company', 'Azienda'), ('non_profit', 'Ente / cooperativa')], default='company', max_length=32, verbose_name='tipo cliente')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='referente')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='telefono')),
                ('address', models.TextField(blank=True, verbose_name='indirizzo')),
                ('tax_code', models.CharField(blank=True, max_length=64, verbose_name='codice fiscale / partita IVA')),
                ('notes', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clienti',
                'ordering': ['name'],
            },
        ),
    ]
