# Generated by Codex on 2026-07-07

import apps.customers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAgreement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="nome accordo")),
                ("price_list_name", models.CharField(blank=True, max_length=255, verbose_name="listino collegato")),
                ("starts_on", models.DateField(blank=True, null=True, verbose_name="data inizio")),
                ("ends_on", models.DateField(blank=True, null=True, verbose_name="data fine")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bozza"),
                            ("active", "Attivo"),
                            ("expired", "Scaduto"),
                            ("paused", "Sospeso"),
                            ("renewed", "Rinnovato"),
                            ("closed", "Chiuso"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="stato",
                    ),
                ),
                ("general_terms", models.TextField(blank=True, verbose_name="condizioni generali")),
                ("commercial_notes", models.TextField(blank=True, verbose_name="note commerciali")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creato il")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="aggiornato il")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="customers.customer",
                        verbose_name="cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "accordo cliente",
                "verbose_name_plural": "accordi cliente",
                "ordering": ["customer", "-starts_on", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerCommercialDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="nome documento")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("nda", "NDA"),
                            ("commercial_agreement", "Accordo commerciale"),
                            ("frame_agreement", "Accordo quadro"),
                            ("special_terms", "Condizioni particolari"),
                            ("signed_price_list", "Listino firmato"),
                            ("engagement_letter", "Lettera di incarico"),
                            ("other", "Altro"),
                        ],
                        max_length=64,
                        verbose_name="tipo documento",
                    ),
                ),
                ("issued_on", models.DateField(blank=True, null=True, verbose_name="data emissione")),
                ("signed_on", models.DateField(blank=True, null=True, verbose_name="data firma")),
                ("expires_on", models.DateField(blank=True, null=True, verbose_name="data scadenza")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bozza"),
                            ("sent", "Inviato"),
                            ("signed", "Firmato"),
                            ("active", "Attivo"),
                            ("expired", "Scaduto"),
                            ("replaced", "Sostituito"),
                            ("archived", "Archiviato"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="stato",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to=apps.customers.models.commercial_document_upload_path,
                        verbose_name="file allegato",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="note")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creato il")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="aggiornato il")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commercial_documents",
                        to="customers.customer",
                        verbose_name="cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento commerciale cliente",
                "verbose_name_plural": "documenti commerciali cliente",
                "ordering": ["customer", "-issued_on", "name"],
            },
        ),
    ]
