services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_ENV: prod
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
      - media_data:/app/media
    env_file:
      - .env
    environment:
      DJANGO_ENV: prod
    depends_on:
      - db
      - redis

  beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/app
      - media_data:/app/media
    env_file:
      - .env
    environment:
      DJANGO_ENV: prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-b3dlab}
      POSTGRES_USER: ${POSTGRES_USER:-b3dlab}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-b3dlab}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  media_data:
