# Generated by Django 5.1.15 on 2026-07-06 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True, verbose_name='numero commessa')),
                ('status', models.CharField(choices=[('todo', 'Da fare'), ('design', 'In progettazione'), ('printing', 'In stampa'), ('post_processing', 'In post-processing'), ('ready', 'Pronto'), ('delivered', 'Consegnato'), ('paused', 'Sospeso'), ('cancelled', 'Annullato')], default='todo', max_length=32, verbose_name='stato')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='data avvio')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='consegna prevista')),
                ('delivered_at', models.DateField(blank=True, null=True, verbose_name='data consegna')),
                ('operational_notes', models.TextField(blank=True, verbose_name='note operative')),
                ('final_notes', models.TextField(blank=True, verbose_name='note finali')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='customers.customer', verbose_name='cliente')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='estimates.estimate', verbose_name='preventivo')),
                ('selected_configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='estimates.estimateconfiguration', verbose_name='configurazione scelta')),
            ],
            options={
                'verbose_name': 'commessa',
                'verbose_name_plural': 'commesse',
                'ordering': ['-created_at'],
            },
        ),
    ]
