# Generated by Django 5.1.15 on 2026-07-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('status', models.CharField(choices=[('started', 'Avviata'), ('success', 'Completata'), ('failed', 'Errore')], max_length=32, verbose_name='stato')),
                ('message', models.TextField(blank=True, verbose_name='messaggio')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='dati')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='avviata il')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='terminata il')),
            ],
            options={
                'verbose_name': 'log automazione',
                'verbose_name_plural': 'log automazioni',
                'ordering': ['-started_at'],
            },
        ),
    ]
