# Generated by Django 5.1.15 on 2026-07-06 20:18

import apps.documents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('document_type', models.CharField(choices=[('internal_estimate', 'Preventivo interno'), ('consulting_estimate', 'Preventivo consulenza'), ('supply_estimate', 'Preventivo fornitura/artigiano'), ('delivery', 'Documento di consegna'), ('technical_report', 'Relazione tecnica'), ('fiscal_future', 'Documento fiscale futuro')], max_length=64, verbose_name='tipo documento')),
                ('profile', models.CharField(blank=True, max_length=64, verbose_name='profilo')),
                ('template_file', models.FileField(upload_to=apps.documents.models.template_upload_path, verbose_name='file template DOCX')),
                ('template_version', models.CharField(default='v1', max_length=32, verbose_name='versione template')),
                ('active', models.BooleanField(default=True, verbose_name='attivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='caricato il')),
                ('notes', models.TextField(blank=True, verbose_name='note')),
            ],
            options={
                'verbose_name': 'template documento',
                'verbose_name_plural': 'template documenti',
                'ordering': ['document_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('internal', 'Interno dettagliato'), ('consulting', 'Consulenza'), ('supply', 'Fornitura / artigiano'), ('delivery', 'Consegna'), ('technical_report', 'Relazione tecnica')], max_length=64, verbose_name='tipo documento')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versione')),
                ('docx_file', models.FileField(blank=True, upload_to=apps.documents.models.generated_document_path, verbose_name='file DOCX')),
                ('pdf_file', models.FileField(blank=True, upload_to=apps.documents.models.generated_document_path, verbose_name='file PDF')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='generato il')),
                ('notes', models.TextField(blank=True, verbose_name='note')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='estimates.estimate', verbose_name='preventivo')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.documenttemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'documento generato',
                'verbose_name_plural': 'documenti generati',
                'ordering': ['-generated_at'],
                'unique_together': {('estimate', 'document_type', 'version')},
            },
        ),
    ]
