# Generated by Django 5.1.15 on 2026-07-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('material_type', models.CharField(blank=True, max_length=128, verbose_name='tipo')),
                ('brand', models.CharField(blank=True, max_length=128, verbose_name='marca')),
                ('color', models.CharField(blank=True, max_length=128, verbose_name='colore')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo per kg/litro')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='fornitore')),
                ('technical_notes', models.TextField(blank=True, verbose_name='note tecniche')),
                ('uv_resistance', models.CharField(blank=True, max_length=255, verbose_name='resistenza UV')),
                ('temperature_notes', models.CharField(blank=True, max_length=255, verbose_name='temperatura')),
                ('available', models.BooleanField(default=True, verbose_name='disponibile')),
            ],
            options={
                'verbose_name': 'materiale',
                'verbose_name_plural': 'materiali',
                'ordering': ['name', 'brand', 'color'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('model', models.CharField(blank=True, max_length=255, verbose_name='modello')),
                ('ownership', models.CharField(choices=[('owned', 'Propria'), ('customer', 'Cliente'), ('loan', 'Comodato'), ('other', 'Altro')], default='owned', max_length=32, verbose_name='proprieta')),
                ('build_volume', models.CharField(blank=True, max_length=128, verbose_name='volume di stampa')),
                ('enclosed_chamber', models.BooleanField(default=False, verbose_name='camera chiusa')),
                ('supported_materials', models.TextField(blank=True, verbose_name='materiali supportati')),
                ('hourly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo orario stimato')),
                ('estimated_power_watts', models.PositiveIntegerField(blank=True, null=True, verbose_name='consumo stimato watt')),
                ('notes', models.TextField(blank=True, verbose_name='note')),
                ('active', models.BooleanField(default=True, verbose_name='attiva')),
            ],
            options={
                'verbose_name': 'stampante / strumentazione',
                'verbose_name_plural': 'stampanti / strumentazioni',
                'ordering': ['name'],
            },
        ),
    ]
