# Generated by Codex on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="cost_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Costo di acquisto o riferimento interno prima di scarti e maggiorazioni.",
                max_digits=10,
                verbose_name="costo base per kg/litro",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="pricing_notes",
            field=models.TextField(blank=True, verbose_name="note costo materiale"),
        ),
        migrations.AddField(
            model_name="material",
            name="waste_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentuale prudenziale per supporti, prove, sfridi o materiale non recuperabile.",
                max_digits=5,
                verbose_name="scarto / extra materiale %",
            ),
        ),
        migrations.AlterField(
            model_name="printer",
            name="hourly_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Quota oraria principale: ammortamento, noleggio o stima interna gia nota.",
                max_digits=10,
                verbose_name="costo orario base",
            ),
        ),
        migrations.AddField(
            model_name="printer",
            name="economic_notes",
            field=models.TextField(blank=True, verbose_name="note economiche"),
        ),
        migrations.AddField(
            model_name="printer",
            name="electricity_cost_per_kwh",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Costo energia usato per stimare la quota elettrica oraria.",
                max_digits=10,
                verbose_name="costo energia kWh",
            ),
        ),
        migrations.AddField(
            model_name="printer",
            name="failure_rate_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentuale prudenziale per prove fallite, riavvii o rilavorazioni.",
                max_digits=5,
                verbose_name="rischio fallimento %",
            ),
        ),
        migrations.AddField(
            model_name="printer",
            name="maintenance_cost_per_hour",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Quota prudenziale per ricambi, ugelli, usura e manutenzione ordinaria.",
                max_digits=10,
                verbose_name="manutenzione per ora",
            ),
        ),
    ]
