# Generated by Django 5.1.15 on 2026-07-06 20:18

import apps.files.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('estimates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('file_type', models.CharField(choices=[('3mf', '3MF'), ('gcode', 'G-code'), ('stl', 'STL'), ('pdf', 'PDF'), ('docx', 'DOCX'), ('image', 'Immagine'), ('other', 'Altro')], default='other', max_length=32, verbose_name='tipo file')),
                ('original_file', models.FileField(upload_to=apps.files.models.original_upload_path, verbose_name='file originale')),
                ('preview_file', models.FileField(blank=True, upload_to=apps.files.models.preview_upload_path, verbose_name='preview')),
                ('extracted_metadata', models.JSONField(blank=True, default=dict, verbose_name='metadati estratti')),
                ('processing_status', models.CharField(choices=[('pending', 'Da elaborare'), ('processing', 'In elaborazione'), ('ready', 'Pronto'), ('failed', 'Errore'), ('skipped', 'Saltato')], default='pending', max_length=32, verbose_name='stato elaborazione')),
                ('processing_error', models.TextField(blank=True, verbose_name='errore elaborazione')),
                ('notes', models.TextField(blank=True, verbose_name='note')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='caricato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_files', to='customers.customer', verbose_name='cliente')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_files', to='estimates.estimate', verbose_name='preventivo')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_files', to='jobs.job', verbose_name='commessa')),
            ],
            options={
                'verbose_name': 'file allegato',
                'verbose_name_plural': 'file allegati',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
